### ISSUE TITLE
[electron] Can't start the with-electron example.

### ISSUE THREAD

**Issue by yungkittty** [expo/examples#40]
Hi,

I'm trying to setup expo with electron.

I've followed this : https://docs.expo.io/versions/latest/guides/using-electron/.

But it won't start due to :

```
┏ Renderer -------------------

  Error: Cannot find entry file index.ts (or main.ts, or app.ts, or index.js, or main.js, or app.js)
      at computeEntryFile (/home/x/Clones/test/node_modules/electron-webpack/src/main.ts:389:11)
      at WebpackConfigurator.configure (/home/x/Clones/test/node_modules/electron-webpack/src/main.ts:222:29)
      at configure (/home/x/Clones/test/node_modules/electron-webpack/src/main.ts:376:10)

┗ ----------------------------
```

I've tried to start your example, without success.

Even tho I've fresh clone, yarn install and followed this [README.md](https://github.com/expo/examples/tree/master/with-electron).

I know I could workaround it by adding a index.js but from the documentation it's suppose to find the App.js by its own.

Any idea?

**Comment by schellack** [comment]
I was able to get it working. Here are the steps I followed:

1.  Run `expo init ElectronExample` and complete the wizard (I select the "managed workflow" and the "tabs" template, just to have something there at the start).
2.  `cd ElectronExample`
3.  `yarn add -D @expo/electron-adapter`
4.  `yarn expo-electron`
5.  Get weird errors starting electron ("Error while loading shared libraries: libnss3.so") because I'm on Windows using WSL for my terminal.
6.  To fix the weird errors, reinstall electron with yarn in a Windows command prompt because of [this](https://github.com/electron-userland/electron-prebuilt/issues/260#issue-232100980).
7.  Realize that this added the latest version of electron, and the version of electron in the [example repo](https://github.com/expo/examples/tree/master/with-electron) here is older. So I downgrade to `6.0.12` and yarn install again.
8.  Compare my `package.json` to the one in this sample repo and see that `@expo/webpack-config` is missing, so install it with `yarn add @expo/webpack-config`.
9.  Run `yarn expo-electron start` from the Windows command prompt (it won't work for me from WSL terminal)

A key thing for me was comparing this repo example to my "clean" project where I did `expo init` and followed the instructions from the [guide](https://docs.expo.io/versions/latest/guides/using-electron/).

![image](https://user-images.githubusercontent.com/70819/71121847-e3e4d780-21a4-11ea-870b-54896445602d.png)

**Comment by yungkittty** [comment]
I've followed the same documentation on my side too. However, I've always the same error about a main.js(|| ts) missing. That's why I've looked for an example like the one on this repository. Still, I've always the same error even though I've fresh clone this repository and `yarn desktop`. @EvanBacon is it suppose to be a working example or it's just a template (so the index.js would be missing)?
