### ISSUE TITLE
examples/with-drawer-navigation/ - Several warnings / errors - Application does not run

### ISSUE THREAD

**Issue by stevus** [expo/examples#402]
**Describe the bug**

The error messages

```
Uncaught Error: Module parse failed: Unexpected token (4:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export * from "./reanimated1";
| export * from "./reanimated2";
> export * as default from "./Animated";
    at ./node_modules/react-native-reanimated/lib/index.web.js (utils.ts:24:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js (DrawerToggleButton.tsx:54:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/@react-navigation/drawer/lib/module/navigators/createDrawerNavigator.js (index.tsx:23:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/@react-navigation/drawer/lib/module/index.js (index.tsx:4:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./App.js (App.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/expo/AppEntry.js (AppEntry.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at 1 (log.js:59:1)
    at __webpack_require__ (bootstrap:789:1)
    at bootstrap:856:1
    at bootstrap:856:1
```

```
Uncaught ReferenceError: process is not defined
    at 4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at 8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at 8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at e.onload (index.js:1:1)
```

```
index.js:1 ./node_modules/react-native-reanimated/lib/index.web.js 4:9
Module parse failed: Unexpected token (4:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export * from "./reanimated1";
| export * from "./reanimated2";
> export * as default from "./Animated";
```

```
Could not get the stack frames of error: TypeError: Cannot read properties of null (reading 'length')
    at G (index.js:1:1)
    at index.js:1:1
    at Array.map (<anonymous>)
    at index.js:1:1
    at c (index.js:1:1)
    at Generator._invoke (index.js:1:1)
    at Generator.next (index.js:1:1)
    at D (index.js:1:1)
    at i (index.js:1:1)
```

displays in Chrome developer tools.

**To Reproduce**
1. Create a project w/ the source from https://github.com/expo/examples/tree/master/with-drawer-navigation
2. `npm install`
3. `npm run start`
4. Observe nothing renders in Chrome browser
5. Observe error message in Chrome developer tools

**Expected behavior**
Application displays, no warnings in Chrome developer tools.

**Screenshots**

![image](https://user-images.githubusercontent.com/1261603/208873730-88659a6f-f652-4ab8-958e-5a057076bdc6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.96

**Comment by stevus** [comment]
The application seems to crash when only importing the react navigation drawer factory method:

```
import { createDrawerNavigator } from "@react-navigation/drawer";

export default function App() {
  return (
    <div>
      TEST
    </div>
  );
}
```
